# Generated by Django 4.2.2 on 2025-07-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('key', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
