# Generated by Django 4.2.2 on 2025-07-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='key',
            field=models.FloatField(),
        ),
    ]
